### ISSUE TITLE
Function機能の追加について

### ISSUE THREAD

**Issue by YusukeKiyooka** [NaokiTakahashi12/waypoint_manager#4]
waypointごとに行動を選択できるような，機能を追加していただけませんか？
https://github.com/open-rdc/waypoint_nav
こちらではwaypointごとに行動を切り替えながら走行させていました．
例えば，白線前のwaypointまで来たら，カメラで白線を認識し停止するようなことをやっていました．
こちらでも同じように，waypointごとに行動を切り替えるような機能を追加でしていただけませんか？
よろしくお願いします．

**Comment by NaokiTakahashi12** [comment]
いまいちあいまいですが，以下のように理解しました．

 waypoint間に何らかのtopicを受け取った際の挙動をプログラムしたい

この理解であっているようであれば，waypointnごとにプロパティとしてパラメータを設定できます．
この情報は`Waypoint`メッセージに含まれており，waypoint毎に設定できます．
例として，`white_line_stop`などをプロパティに追加することで，`Waypoint`メッセージから停止が必要な区間であるかわかると思います．

つまり，waypointごとの目的地を変換しているのは，[このノード](https://github.com/NaokiTakahashi12/waypoint_manager/blob/main/waypoint_server/src/waypoint_to_posestamped_node.cpp)であるため，`WaypointStamped`を購読するノードを作ることで目的を達成できると思います．

また以下が疑問点になります．

+ 行動は速度指令を指すのか
+ 移動指令はどのノードにするのか

**Comment by haruyama8940** [comment]
ありがとうございます．
概ねその通りです
アドバイスを基に追加を行ってみます

また「行動」については「指示された処理を実行するための速度指令」になります
移動指令に関しては，waypoint_maneger以外の別のノードがおこないます

**Comment by NaokiTakahashi12** [comment]
必要あれば追加を行うので，いったんこのissueはクローズします．
もし，意図がくみ取られていないようであれば再度オープンしてください．
